### PR TITLE
week7

### PR DESCRIPTION
**Pull request by codingzzang123**

### CODE REVIEW

**Review by Yejin-Ha — COMMENTED** [review]
좋아요

**Review by SHJ980818 — COMMENTED** [review]
우왕굳

**Review by da11un — COMMENTED** [review]
fix가 무엇?!

**Review by mki1105 — COMMENTED** [review]
좋아요

**Comment by codingzzang123** [comment]
> fix가 무엇?!

public static int fix(int i) {
		return (i % 10)*10 + ((i/10 + i%10)%10);
	}

this is function fix() 😉

**Pull request merged**
